baseURL = "https://intermezzio.github.io/blog/"
languageCode = "en-us"
title = "Chess Thoughts"
theme = "ananke"
[params]
	post_navigation = true
	thumbnail = "intermezzio_logo.png"
	disqus = "enabled"
[params.sidebar]
    order = [
    	"recent"
    ]
[params.background]
	src = "images/background-blue.jpg"
	fit = "cover"
[params.color]
	main_background = "#101010d5"
	alt_background = "#252525d0"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
	accent = "#1034a6ff"
    accent_text = "#e2e2e2"
[params.fonts]
	header_style = "sans-serif"
	body_style = "sans-serif"
	print_header_style = "slab-serif"
	print_body_style = "sans-serif"

[menu]
	[[menu.main]]
		identifier = "about"
		name = "about"
		url = "/about/"
		weight = -90
	[[menu.main]]
		name = "posts"
		url = "/posts/"
		weight = -100

disqusShortname = "intermezzio"
